routes:

collections:
  /:
    permalink: /photo/{slug}/
    template: index
    filter: primary_tag:photo

  /blog/:
    permalink: /blog/{slug}/
    template: blog
    filter: primary_tag:blog

taxonomies:
  ## Nothing but silence
