routes:
  /blog/:
    controller: channel
    filter: tag:blog

collections:
  /:
    permalink: /photo/{slug}/
    template: index
    filter: tag:photo

  /blog/:
    permalink: /blog/{slug}/
    template: blog
    filter: tag:blog

taxonomies:
  ## Nothing but silence
